# Generated by Django 3.2.16 on 2023-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'MALE'), ('F', 'FEMALE')], max_length=6, null=True),
        ),
    ]
