# Generated by Django 3.2.16 on 2023-01-16 07:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[accounts.models.has11digits]),
        ),
    ]
