# Generated by Django 3.2.16 on 2023-01-16 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
